# Generated by Django 5.1.5 on 2025-02-01 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='question_fr',
            field=models.TextField(blank=True, null=True),
        ),
    ]
